### ISSUE TITLE
Install/update the edsight MLHUB package when ~/.mlhub/edsight exists

### ISSUE THREAD

**Issue by cdawei** [anusii/edsight#16]
When the directory `~/.mlhub/edsight` exists, command `ml install anusii/edsight` does not seem to fetch the edsight repo and then install it.

My workaround is `rm -rf ~/.mlhub/edsight && ml install anusii/edsight`

**Comment by gjwgit** [comment]
Any more details? I am not able to replicate this. You can also remove an mlhub package with `ml uninstall edsight`.

```
12 Jan 10:27:08 gjw@yoga ~$ ll ~/.mlhub/edsight/
total 16K
-rw-r----- 1 gjw gjw    0 Jan 11 14:52 demo.R
-rw-r----- 1 gjw gjw 2.0K Jan 11 14:52 itemsets.R
-rw-r----- 1 gjw gjw  711 Jan 11 14:52 MLHUB.yaml
-rw-r----- 1 gjw gjw  779 Jan 11 14:52 README.md
-rw-r----- 1 gjw gjw 2.3K Jan 11 14:52 train.R

12 Jan 10:27:13 gjw@yoga ~$ ml install anusii/edsight
Replace 'edsight' version '0.1.2' with version '0.1.2' [Y/n]? 

Package https://codeload.github.com/anusii/edsight/zip/main

Downloading 'edsight-main.zip' ...

Extracting 'edsight-main.zip' ...

Found 'edsight' version 0.1.2.

Installed 'edsight' into '/home/gjw/.mlhub/edsight/' (5,739 bytes).

To configure the package:

  $ ml configure edsight

12 Jan 10:27:35 gjw@yoga ~$ ll ~/.mlhub/edsight/
total 16K
-rw-r----- 1 gjw gjw    0 Jan 12 10:27 demo.R
-rw-r----- 1 gjw gjw 2.0K Jan 12 10:27 itemsets.R
-rw-r----- 1 gjw gjw  711 Jan 12 10:27 MLHUB.yaml
-rw-r----- 1 gjw gjw  779 Jan 12 10:27 README.md
```

**Comment by cdawei** [comment]
In my case, I manually created a directory `.mlhub/edsight` and put a csv file in it. I did notice that `ml install anusii/edsight` complained that no `MLHUB.yaml` exists. This is likely due to my `.mlhub/edsight` is not a properly installed MLHUB package.

**Comment by gjwgit** [comment]
Thanks for that.

Yes. MLHub assumes it controls the .mlhub directory and if it exists then it expects to find `MLHUB.yaml`. 

I've updated the error message on INSTALL to identify where the MLHUB.yaml file is missing from:

```
$ ml install anusii/edsight
mlhub: No 'MLHUB.yaml' description file found in /home/gjw/.mlhub/.
```
