### ISSUE TITLE
Installing MLHUB on Ubuntu 20.04 - minor tweaks

### ISSUE THREAD

**Issue by cdawei** [anusii/edsight#17]
Following https://survivor.togaware.com/mlhub/installing-mlhub.html, there are two minor tweaks I needed:
- use `echo 'PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc && source ~/.bashrc` so that the `ml` command will be in the PATH
- I also need to install `testthat` before installing `mlhub` R package. i.e., `install.packages("testthat")` and then `devtools::install_github("mlhubber/mlhub@main", quiet=TRUE)`

**Comment by gjwgit** [comment]
Thanks for the updates @cdawei. Done.
